service_info/service_info/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticket/', include('ticket.urls')),
]

service_info/ticket/urls.py
from django.urls import path
from . import views

app_name = 'ticket'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create_ticket/', views.create_ticket, name='create_ticket'),
    path('read_ticket/<int:ticket_id>/', views.read_ticket, name='read_ticket'),
    path('delete_ticket/<int:ticket_id>/', views.delete_ticket, name='delete_ticket'),
    path('update_ticket/<int:ticket_id>/', views.update_ticket, name='update_ticket'),
    path('search_ticket', views.search_ticket, name='search_ticket'),

    path('traitement_ticket', views.traitement_ticket, name='traitement_ticket'),
    path('traitement_category', views.traitement_category, name='traitement_category'),

    path('create_category/', views.create_category, name='create_category'),
    path('read_category/<int:category_id>/', views.read_category, name='read_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('search_category', views.search_category, name='search_category'),
]

service_info/ticket/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    priority_choices = (
        (1, 'Low'),
        (2, 'Medium'),
        (3, 'High'),
    )
    priority = models.IntegerField(choices=priority_choices, default=1)
    def __str__(self):
        return self.name

class Ticket(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.CharField(max_length=200)
    status_choices = (
        ('OPEN', 'Open'),
        ('IN_PROGRESS', 'In Progress'),
        ('CLOSED', 'Closed'),
    )
    status = models.CharField(max_length=20, choices=status_choices, default='OPEN')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} - {self.description[:50]} - {self.created_at} - {self.author} - {self.status}"

service_info/ticket/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from . import models
from django import forms

class TicketForm(ModelForm):
    class Meta:
        model = models.Ticket
        fields = ('title', 'description', 'author', 'status', 'category')

        labels = {
            'title': _('Titre'),
            'description': _('Description'),
            'author': _('Auteur'),
            'status': _('Statut'),
            'category': _('Catégorie'),
        }

class CategoryForm(ModelForm):
    class Meta:
        model = models.Category
        fields = ('name', 'description', 'priority')
        labels = {
            'name': 'Nom',
            'description': 'Description',
            'priority': 'Priorité',
        }
        
class TicketIdForm(forms.Form):
    ticket_id = forms.IntegerField(label='ID du ticket')
    actions = (
        ('read_ticket', 'Lire'),
        ('delete_ticket', 'Supprimer'),
        ('update_ticket', 'Modifier'),
    )
    action = forms.ChoiceField(choices=actions, label='Action')
    
class CategoryIdForm(forms.Form):
    category_id = forms.IntegerField(label='ID de la catégorie')
    actions = (
        ('read_category', 'Lire'),
        ('delete_category', 'Supprimer'),
        ('update_category', 'Modifier'),
    )
    action = forms.ChoiceField(choices=actions, label='Action')

service_info/ticket/views.py
from django.shortcuts import render, redirect
from .models import Ticket, Category
from .forms import TicketForm, CategoryForm, TicketIdForm, CategoryIdForm

def index(request):
    tickets = Ticket.objects.all()
    return render(request, 'ticket/index.html', {'tickets': tickets})

def create_ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = TicketForm()
    return render(request, 'ticket/create_ticket.html', {'form': form})

def read_ticket(request, ticket_id):
    if request.method == 'GET':
        ticket = Ticket.objects.get(id=ticket_id)
        return render(request, 'ticket/affiche_ticket.html', {'ticket': ticket})

def delete_ticket(request, ticket_id):
    if request.method == 'GET':
        ticket = Ticket.objects.get(id=ticket_id)
        ticket.delete()
        return redirect('ticket:index')
    
def update_ticket(request, ticket_id):
    ticket_a_modifier = Ticket.objects.get(id=ticket_id)

    if request.method == 'POST':
        lform = TicketForm(request.POST, instance=ticket_a_modifier)
        if lform.is_valid():
            lform.save()
            return redirect('ticket:index')
    else:
        return render(request, 'ticket/affiche_ticket.html', {'ticket': ticket_a_modifier})

    return render(request, 'ticket/update_ticket.html', {'form': lform, 'ticket': ticket_a_modifier})
    

def traitement_ticket(request):
    lform = TicketForm(request.POST)
    if lform.is_valid():
        ticket = lform.save()
        return render(request, 'ticket/affiche_ticket.html', {'ticket': ticket})
    else:
        return render(request, 'ticket/create_ticket.html', {'form': lform})
    
def search_ticket(request):
    if request.method == 'POST':
        lform = TicketIdForm(request.POST)
        if lform.is_valid():
            ticket_id = lform.cleaned_data['ticket_id']
            action = lform.cleaned_data['action']
            
            if action == 'read_ticket':
                return redirect('ticket:read_ticket', ticket_id=ticket_id)
            elif action == 'delete_ticket':
                return redirect('ticket:delete_ticket', ticket_id=ticket_id)
            elif action == 'update_ticket':
                return redirect('ticket:update_ticket', ticket_id=ticket_id)
            
    else:
        lform = TicketIdForm()
    return render(request, 'ticket/search_ticket.html', {'form': lform})

def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = CategoryForm()
    return render(request, 'ticket/create_category.html', {'form': form})

def traitement_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            return render(request, 'ticket/affiche_category.html', {'category': category})
    else:
        form = CategoryForm()
    return render(request, 'ticket/create_category.html', {'form': form})

def read_category(request, category_id):
    category = Category.objects.get(id=category_id)
    return render(request, 'ticket/affiche_category.html', {'category': category})

def delete_category(request, category_id):
    if request.method == 'GET':
        category = Category.objects.get(id=category_id)
        category.delete()
        return redirect('ticket:index')

def update_category(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('ticket:search_category')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'ticket/update_category.html', {'form': form, 'category': category})

def search_category(request):
    categories = Category.objects.all()
    lform = CategoryIdForm()

    if request.method == 'POST':
        lform = CategoryIdForm(request.POST)
        if lform.is_valid():
            category_id = lform.cleaned_data['category_id'] ## recupere l'id de la categorie
            action = lform.cleaned_data['action']
            category = Category.objects.filter(id=category_id).first()
            if category:
                if action == 'read_category':
                    return redirect('ticket:read_category', category_id=category_id)
                elif action == 'delete_category':
                    return redirect('ticket:delete_category', category_id=category_id)
                elif action == 'update_category':
                    return redirect('ticket:update_category', category_id=category_id)
            else:
                return render(request, 'ticket/search_category.html')

    return render(request, 'ticket/search_category.html', {'form': lform, 'categories': categories})

service_info/ticket/templates/ticket/affiche_category.html
{% extends 'ticket/main.html' %}

{% block title %}Categories - Ticketing{% endblock %}

{% block content %}
<h1>Affiche d'une catégorie</h1>
<div class="ticket-container">
    <div class="ticket">
        <p>Category: {{ category.name }}</p>
        <p>Description: {{ category.description }}</p>
        <p>Priority: {{ category.priority }}</p>
    </div>
</div>
{% endblock %}

service_info/ticket/templates/ticket/affiche_ticket.html
{% extends 'ticket/main.html' %}

{% block title %}Ticket - Ticketing{% endblock %}

{% block content %}
    <h1>Ticket Detail</h1>
    <div class="ticket-container">
        <div class="ticket">
            <p><strong>Title:</strong> {{ ticket.title }}</p>
            <p><strong>Description:</strong> {{ ticket.description }}</p>
            <p><strong>Author:</strong> {{ ticket.author }}</p>
            <p><strong>Status:</strong> {{ ticket.status }}</p>
            <p><strong>Category:</strong> {{ ticket.category }}</p>
        </div>
    </div>
{% endblock %}

service_info/ticket/templates/ticket/create_category.html
{% extends 'ticket/main.html' %}

{% block title %}Créer categorie - Ticketing{% endblock %}

{% block content %}
    <form method="post" action="/ticket/traitement_category" class="form-add">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Créer une catégorie">
    </form>
{% endblock %}

service_info/ticket/templates/ticket/create_ticket.html
{% extends 'ticket/main.html' %}

{% block title %}Créer ticket - Ticketing{% endblock %}

{% block content %}
    <form method="post" action="/ticket/traitement_ticket" class="form-add">
        {% csrf_token %}
        {{ form.as_ul }}

        <input type="submit" value="Créer un ticket">
    </form>
{% endblock %}

service_info/ticket/templates/ticket/index.html
{% extends 'ticket/main.html' %}

{% block title %}Accueil - Ticketing{% endblock %}


{% block content %}
    <h1>All Tickets</h1>
    <div class="ticket-container">
        {% for ticket in tickets %}
            <div class="ticket">
                <h3>{{ ticket.title }}</h3>
                <p><strong>Description:</strong> {{ ticket.description }}</p>
                <p><strong>Statut:</strong> {{ ticket.status }}</p>
                <p><strong>Créé le:</strong> {{ ticket.created_at }}</p>
                <p><strong>Catégorie:</strong> {{ ticket.category }}</p>
                <p><strong>Auteur:</strong> {{ ticket.author }}</p>
                <p><strong>ID:</strong> {{ ticket.id }}</p>


                <a href="{% url 'ticket:search_ticket' %}" class="index-input">
                    <input type="button" value="Modifier/Supprimer un ticket">
                </a>


            </div>
        {% endfor %}
    </div>
{% endblock %}

service_info/ticket/templates/ticket/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Titre par défaut{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'ticket:index' %}">Accueil</a></li>
            
            <li class="sub-menu">
                <a href="#">Les tickets</a>
                <ul>
                    <li><a href="{% url 'ticket:create_ticket' %}">Créer un ticket</a></li>
                    <li><a href="{% url 'ticket:search_ticket' %}">Manager un ticket</a></li>
                </ul>
            </li>

            <li class="sub-menu">
                <a href="#">Les catégories</a>
                <ul>
                    <li><a href="{% url 'ticket:create_category' %}">Créer une catégorie</a></li>
                    <li><a href="{% url 'ticket:search_category' %}">Voir une catégorie</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</header>

<main>
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

service_info/ticket/templates/ticket/search_category.html
{% extends 'ticket/main.html' %}

{% block title %}Acceuil - Ticketing{% endblock %}

{% block content %}
    <h1>Panneau de configuration des catégories :</h1>
    <form method="post" action="{% url 'ticket:search_category' %}?category_id={{ form.category_id.value }}" class="form-add">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Chercher une categorie">
    </form>

    <h1>Toutes les catégories :</h1>
    <div class="ticket-container">
        {% for category in categories %}
            <div class="ticket">
                <h3>{{ category.name }}</h3>
                <p><strong>ID:</strong> {{ category.id }}</p>
            </div>
        {% endfor %}
{% endblock %}

service_info/ticket/templates/ticket/search_ticket.html
{% extends 'ticket/main.html' %}

{% block title %}Acceuil - Ticketing{% endblock %}

{% block content %}
    <h1>Panneau de configuration des tickets :</h1>
    <form method="post" action="{% url 'ticket:search_ticket' %}?ticket_id={{ form.ticket_id.value }}" class="form-add">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Chercher un ticket">
    </form>
{% endblock %}

service_info/ticket/templates/ticket/update_category.html
{% extends 'ticket/main.html' %}

{% block title %}Accueil - Ticketing{% endblock %}


{% block content %}
<form method="post" action="{% url 'ticket:update_category' category_id=category.id %}" class="form-add">
    {% csrf_token %}
    {{ form.as_ul }}

    <input type="submit" value="Mettre à jour la categorie">
</form>

{% endblock %}

service_info/ticket/templates/ticket/update_ticket.html
{% extends 'ticket/main.html' %}

{% block title %}Accueil - Ticketing{% endblock %}


{% block content %}
<form method="post" action="{% url 'ticket:update_ticket' ticket_id=ticket.id %}" class="form-add">
    {% csrf_token %}
    {{ form.as_ul }}

    <input type="submit" value="Mettre à jour le ticket">
</form>
{% endblock %}